# Our global, build settings
[build]
   base    = "code"        # run the build from this directory
   publish = "public"      # the output directory to push to the CDN after the build
   command = "deploy site"  # the command to build our site
  
